session:
  name: session_id
  secret_key: abc123
db:
  default:
    type: mysql
    host: 127.0.0.1
    port: 3306
    user: root
    password: 123456
    dbname: oauth2
redis:
  default:
    addr: 127.0.0.1:6379
    password: 
    db: 0
oauth2:
  client:
    - id: test_client_1
      secret: test_secret_1
      name: 测试应用1 
      domain: http://client1.com:9093
      scope:
        - id: all
          title: 用户账号, 手机, 权限, 角色等信息

    - id: test_client_2
      secret: test_secret_2
      name: 测试应用2 
      domain: http://client2.com:9094
      scope:
        - id: all
          title: 用户账号, 手机, 权限, 角色等信息

    - id: test_client_3
      secret: test_secret_3
      name: 测试应用3
      domain: http://localhost:8080
      scope:
        - id: all
          title: 用户账号, 手机, 权限, 角色等信息
